name: Fetch Analytics

on:
  schedule:

    # Runs on the 1st of every month at 2:00 AM
    # If the person who last edited this line is no longer in the organization, cron is disabled.
    # To re-enable it, make a change to it (add 1 minute for example)
    # Cron formatting: https://crontab.cronhub.io/
    # Last person to change this: Richie Motorgeanu
    - cron: "0 9 * * *"
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  get_analytics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4
        
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install tqdm
          pip install beautifulsoup4
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: execute py script
        run: |
          python scraper.py                                    # Create the data
          git config user.name github-actions                  # And commit the data to the repo
          git config user.email github-actions@github.com
          git pull
          git add .
          git commit -m "crongenerated"
          git push
